### ISSUE TITLE
Does this work with newer versions?

### ISSUE THREAD

**Issue by jwanglof** [deepstreamIO/deepstream.io-provider-search-rethinkdb#2] opened 2015-12-03 15:53 UTC
I'm trying to use the search-provider from NPM (version 0.1.2) with Deepstream (version 0.6.0) and Deepstream client (version 0.3.5) and I keep getting an empty array when I'm calling `.getEntries()`:

```
4:48:21 PM:924 | Found 1 initial matches for search?{"table":"user","query":[["username","eq","a@a.com"]]}
Error: entries must be an array of record names
  at List.setEntries (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/deepstream.io-client-js/src/record/list.js:85:10)
  at Search._populateList (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/deepstream.io-provider-search-rethinkdb/src/search.js:123:13)
  at Search._processInitialValues (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/deepstream.io-provider-search-rethinkdb/src/search.js:101:8)
  at tryCatcher (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/util.js:26:23)
  at Promise.successAdapter (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/nodeify.js:23:30)
  at Promise._settlePromiseAt (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/promise.js:579:21)
  at Promise._settlePromiseAtPostResolution (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/promise.js:245:10)
  at Async._drainQueue (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/async.js:128:12)
  at Async._drainQueues (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/home/johan/Development/mail2/briteback/repos/briteback-setting/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

This is my search-provider-conf:

```
var searchProvider = new SearchProvider({
  logLevel: 3,
  deepstreamClient: DSClientFrontend,
  rethinkdbConnectionParams: {
    host: config.db.host,
    port: config.db.port,
    db: config.db.name
  }
});
```

(`DSClientFrontend` is a started and signed-in Deepstream Client)

This is how I'm using it:

```
var queryString = JSON.stringify({
  table: 'user',
  query: [
    ['username', 'eq', 'a@a.com']
  ]
});
var test = deepstreamClient.record.getList('search?' + queryString);
test.whenReady(() => {
  console.log(hej.getEntries());
});
```

**Comment by yasserf** [comment] 2016-06-30 18:17
Can you retry with 1.0 for all versions? Just realised this will require a fix on rethinkdb-provider since it doesn't use the latest client, so might need to wait until that gets published too.

PS. Sorry for the long reply time...

**Comment by yasserf** [comment] 2016-07-28 08:05
This works for versions 1.0 and above, closing but feel free to open if that isn't the case

**Comment by fgc-** [comment] 2016-09-17 17:59
I am sorry to get exactly the same issue with search-provider v1.1.1 and the following config:

{
    "deepstreamVersion": "1.1.0",
    "gitRef": "a7c6e5628c47876d0b292f72aac98240bc2ed2a9",
    "buildTime": "Fri Sep 09 2016 08:02:56 GMT+0000 (UTC)",
    "platform": "linux",
    "arch": "x64",
    "nodeVersion": "v4.5.0",
    "libs": [
        "deepstream.io-cache-memcached:1.0.0",
        "deepstream.io-cache-redis:1.0.0",
        "deepstream.io-logger-winston:1.1.0",
        "deepstream.io-msg-redis:1.0.1",
        "deepstream.io-storage-rethinkdb:1.0.2",
        "uws:0.8.0"
    ]
}

Here is the detailed log:

19:42:56:602 | Initialising RethinkDb Connection
19:42:56:654 | RethinkDb connection established
19:42:56:655 | Initialising Deepstream connection
19:42:56:676 | Connection to deepstream established
19:42:56:676 | listening for search[\?].*
19:42:56:680 | rethinkdb search provider ready
19:43:26:249 | received subscription for search?{"table":"zzz","query":[["language","eq","de"]]}
19:43:26:291 | Found 24 initial matches for search?{"table":"zzz","query":[["language","eq","de"]]}
/server/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: entries must be an array of record names
    at List.setEntries (/server/node_modules/deepstream.io-client-js/src/record/list.js:86:10)
    at Search._populateList (/server/node_modules/deepstream.io-provider-search-rethinkdb/src/search.js:123:14)
    at Search._processInitialValues (/server/node_modules/deepstream.io-provider-search-rethinkdb/src/search.js:101:10)
    at tryCatcher (/server/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/server/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/server/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/server/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/server/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/server/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/server/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback](timers.js:514:5)

**Comment by jwanglof** [comment] 2016-09-18 09:03
Sorry for not answering, but I've switched jobs where we don't use Deepstream (I'm sad to say, tbh). Good luck! =)

**Comment by yasserf** [comment] 2016-09-18 09:12
@jwanglof No worries, shame! =(

@fgc- are you running it against master or the last release?

**Comment by fgc-** [comment] 2016-09-18 13:23
@jwanglof no problem for me either, i just thought it was more judicious to comment this issue than to open a new one.

@yasserf  i am using the latest npm release.

**Comment by fgc-** [comment] 2016-09-29 20:27
@yasserf for your information, i get the same result using master.
This is so frustrating...deepstream is a stunning piece of work, and i am really awaiting a usable search solution.

**Comment by yasserf** [comment] 2016-10-04 12:25
@fgc- hey, apologies for the late response, we were focusing on getting 1.1.1 out which consumed all of our resources. Will be focusing on getting a release out for this by end of this week.

It seems this should be quite easy to reproduce, can you state the actually steps you done?

**Comment by fgc-** [comment] 2016-10-04 19:15
Don't worry @yasserf , I know you are a small team compared to the scale of the project: so many connectors, modules and different languages...Do you sometimes sleep?
Moreover, I am not sure I need constantly updated search results anymore; I tried a simple rpc with a r request and everything works fine.

Anyway: regarding the steps, it is actually simple. I copied and paste the "configuration" part of the module's README and launched the js file through an independent nodemon process.
I then executed a simple query:

var query = JSON.stringify({
    table: 'zzz',
    query: [
        ['language', 'eq', 'fr']
    ]
});
client
    .getList('search?' + query)
    .whenReady(list => {console.log(list.getEntries();});

I got the results that i logged in my previous post on the server-side; on the browser-side, i got an empty list, with an "Unknown action SH MESSAGE_PARSE_ERROR X".

Hope this help.

**Comment by yasserf** [comment] 2016-10-10 09:43
@fgc- we just released a new version of the provider, be great if you could let us know if this fixes it. Thanks!

**Comment by fgc-** [comment] 2016-10-11 21:33
After upgrading to deepstream to 1.1.1 and the search provider to 1.2.0 I no longer get the error message...but I don't get any result either :/

Here is my own searchProvider.js starting log:

23:00:37:315 | Initialising RethinkDb Connection
23:00:37:374 | RethinkDb connection established
23:00:37:375 | Initialising Deepstream connection
23:00:37:411 | Connection to deepstream established
23:00:37:411 | listening for search[\?].*
23:00:37:413 | rethinkdb search provider ready
23:00:37:416 | received subscription for search?{"table":"zzz","query":[["language","eq","de"]]}
23:00:37:473 | Found 0 initial matches for search?{"table":"zzz","query":[["language","eq","de"]]}

I double-checked the result: previous version of search provider still raised the error - even with 1.2.0 deepstream server - and the equivalent r request actually returns 24 items - as expected.

**Comment by yasserf** [comment] 2016-10-12 09:07
@fgc- Is there any chance you can provide a basic gist or repo showing your client and server code? We have tests that cover this scenario. Will also be a great demo once working to show the setup for future reference.

**Comment by fgc-** [comment] 2016-10-12 20:24
Unfortunately I can not promise anything, mainly because of my availability: I use deeptsream for a personal project. I can not provide my clients and server code as is, so I should reduce my code to a simple case.
Maybe I could try in the course of next week.

**Comment by yasserf** [comment] 2016-10-13 08:44
No worries, we should setup an example/tutorial/demo repo on our side soon anyways which should be a great testbed / place for discussion

**Closed as completed** 2016-11-30 11:22 UTC
